version: '3'
services:
  frontend:
    build: .
    container_name: frontend
    image:  frontend
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./:/frontend
      - /frontend/node_modules
